version: '3.8'

services:
  sender:
    build: ./sender
    container_name: sender
    networks:
      - app-network  
    ports:
      - "5000:5000"  

  receiver:
    build: ./receiver  
    container_name: receiver
    networks:
      - app-network  
    depends_on:
      - sender 
    volumes:
      - data-storage:/data  

networks:
  app-network:  

volumes:
  data-storage:  
